sudo: required
language: node_js
services:
- docker
node_js:
- '7.8'
install:
- npm i
after_success:
- npm run build
- docker build -f Dockerfile -t "$DOCKER_USERNAME"/"$IMAGE_NAME":"$TRAVIS_BUILD_NUMBER"
  .
- docker tag "$DOCKER_USERNAME"/"$IMAGE_NAME":"$TRAVIS_BUILD_NUMBER" "$DOCKER_USERNAME"/"$IMAGE_NAME":latest
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push "$DOCKER_USERNAME"/"$IMAGE_NAME":"$TRAVIS_BUILD_NUMBER"
- docker push "$DOCKER_USERNAME"/"$IMAGE_NAME":latest
before_install:
- openssl aes-256-cbc -K $encrypted_02a30cc79da2_key -iv $encrypted_02a30cc79da2_iv
  -in interact-4a4118c938d7.json.enc -out interact-4a4118c938d7.json -d
