ssr:
  host: localhost
  port: 3000
wds:
  host: localhost
  port: 3001
api:
  host: localhost
  port: 3002
ws: 
  host: localhost
  port: 8080
mongo:
  protocol: mongodb
  host: localhost
  port: 27017
  db: Interact